<?php
session_start();
require_once 'config.php';

if (!isset($_SESSION['admin'])) {
    header('Location: admin_login.php');
    exit();
}

require('fpdf186/fpdf.php');

$id = filter_input(INPUT_GET, 'id', FILTER_VALIDATE_INT);
if (!$id) { die('Invalid complaint ID.'); }

$pdo  = getDB();
$stmt = $pdo->prepare('SELECT * FROM complaints WHERE id = ?');
$stmt->execute([$id]);
$row  = $stmt->fetch();

if (!$row) { die('Complaint not found.'); }

// ── Build PDF ────────────────────────────────────────────────
$pdf = new FPDF();
$pdf->AddPage();

// Header bar
$pdf->SetFillColor(26, 86, 219);
$pdf->SetTextColor(255, 255, 255);
$pdf->SetFont('Arial', 'B', 16);
$pdf->Cell(0, 14, 'CampusCare Complaint Report', 0, 1, 'C', true);

$pdf->SetFillColor(235, 240, 255);
$pdf->SetTextColor(15, 58, 138);
$pdf->SetFont('Arial', '', 10);
$pdf->Cell(0, 8, 'Dayananda Sagar College of Engineering', 0, 1, 'C', true);
$pdf->Ln(8);

// Helper closure
$pdf->SetTextColor(0, 0, 0);

$labelW = 50;
$valueW = 140;

function pdfRow(FPDF $pdf, string $label, string $value, int $lw = 50): void {
    $pdf->SetFont('Arial', 'B', 11);
    $pdf->SetFillColor(248, 250, 252);
    $pdf->Cell($lw, 9, $label, 'LTB', 0, 'L', true);
    $pdf->SetFont('Arial', '', 11);
    $pdf->SetFillColor(255, 255, 255);
    $pdf->Cell(0, 9, $value, 'RTB', 1, 'L', true);
}

pdfRow($pdf, 'Complaint ID', '#' . $row['id']);
pdfRow($pdf, 'Student Name', $row['student_name']);
pdfRow($pdf, 'Department',   $row['department']);
pdfRow($pdf, 'Email',        $row['email']);
pdfRow($pdf, 'Title',        $row['title']);
pdfRow($pdf, 'Status',       $row['status']);
pdfRow($pdf, 'Submitted',    date('d M Y, g:i a', strtotime($row['created_at'])));

$pdf->Ln(6);
$pdf->SetFont('Arial', 'B', 11);
$pdf->SetFillColor(248, 250, 252);
$pdf->Cell(0, 9, 'Description', 'LTR', 1, 'L', true);
$pdf->SetFont('Arial', '', 11);
$pdf->SetFillColor(255, 255, 255);
$pdf->MultiCell(0, 8, $row['description'], 'LBR', 'L', true);

// Footer
$pdf->Ln(10);
$pdf->SetFont('Arial', 'I', 9);
$pdf->SetTextColor(148, 163, 184);
$pdf->Cell(0, 6, 'Generated by CampusCare Management System — ' . date('d M Y'), 0, 1, 'C');

// ── Save & email ─────────────────────────────────────────────
if (!file_exists('pdfs')) { mkdir('pdfs', 0755, true); }
$fileName = 'Complaint_' . $row['id'] . '.pdf';
$filePath = 'pdfs/' . $fileName;
$pdf->Output('F', $filePath);

// Email to student
$subject = 'CampusCare — Complaint Report #' . $row['id'];
$body    = "Dear {$row['student_name']},\n\nPlease find attached the report for your complaint (#{$row['id']}).\n\nTitle: {$row['title']}\nStatus: {$row['status']}\n\nRegards,\nCampusCare Team\nDayananda Sagar College of Engineering";
$headers = 'From: ' . SMTP_FROM;
@mail($row['email'], $subject, $body, $headers);

// ── Stream to browser ────────────────────────────────────────
header('Content-Type: application/pdf');
header('Content-Disposition: attachment; filename="' . $fileName . '"');
readfile($filePath);
exit();
